sudo: required
dist: xenial
language: python
services:
    - docker
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7-dev"
env:
    - TOX_VERSION="tox-2.x"
    - TOX_VERSION="tox-3.x"
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then sudo add-apt-repository ppa:deadsnakes/ppa -y; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then sudo sudo apt-get update; fi
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then source .travis_py37_workaround.sh; fi
    - pip install --constraint "$TOX_VERSION" .
script: "tox"
